### ISSUE TITLE
Suggestion: Classify Fonts

### ISSUE THREAD

**Issue by craigdolphin** [EdiWang/Character-Map-UWP#15]
Hello. Love the app. Such a big improvement. Many thanks.

One suggestion for an improvement would be to allow users to classify a font to be included/excluded from the symbol font list. For example, font awesome doesn't show up in the symbol font list and it would be nice if I could change that.

Anyway, great job :)

**Comment by EdiWang** [comment]
Hi @craigdolphin 

Thank you for your suggestion. Currently the symbol font category is based on the font information that is registered in the system, not manually controlled. For example, Windows does not consider "Segoe UI Emoji" as a symbol font, so it won't show up in the symbol fonts list. 

In order to to that, I will need to implement feature like "white list" to override the system behaviour. It would take some effort, but I think it is worth to add this feature.

**Comment by craigdolphin** [comment]
Hi Edi,

Thanks for explaining it and I’m glad you liked the idea. I wish you the best of luck. 😊

Cheers,
Craig


Sent from Mail for Windows 10

**Comment by EdiWang** [comment]
Fixed in #59
