### ISSUE TITLE
FontAwesome - not all symbols visible

### ISSUE THREAD

**Issue by brano-p** [EdiWang/Character-Map-UWP#37]
For FontAwesome (and possibly others), not all characters are discoverable:
- it's not possible to switch between Solid and Regular
- many characters are missing, i.e. the app shows just few dozen of them from U+F004, the U+F5C8 is shown as the last one available, however the font contains hundreds of symbols from U+F000 up to U+F63C

**Comment by JohnnyWestlake** [comment]
This is largely all fixed in my fork that I'll make a PR back to here for soon - namely the ability to view different variants, and to have different character sets of variants. Rather awkwardly Font Awesome Regular and Font Awesome Solid have a vastly different number of icons despite being in the same family.

**Comment by EdiWang** [comment]
Fixed in #38
